# Generated by Django 4.2.6 on 2023-11-30 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Item",
            new_name="title",
        ),
    ]
